service:
    backendEndpoint: http://internal-ma-noim-alb-pri-1627874572.ap-northeast-1.elb.amazonaws.com
    # backendEndpoint: http://localhost:8081
spring:
    security:
        user:
            name: user
            password: 1qaz"WSX