# 名前
name: "Docker image build and push to DockerHub"

# onセクション：jobsの実行トリガーを記載
on:
  push:
    branches:
      - 'main'  # mainブランチにpushされたときに実行

# jobsセクション
# ：jobセクション配下に1つ以上のjobIDを定義する。各jobIDは並列に処理される。
jobs:
  # jobID
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      -
        name: Build backend-item
        run: |
          cd backend-item
          mvn -B package spring-boot:repackage -DskipTests
      -
        name: Build frontend-webapp
        run: |
          cd frontend-webapp
          mvn -B package spring-boot:repackage -DskipTests
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend-item
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend-item:latest
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-webapp
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend-webapp:latest
          